### ISSUE TITLE
нужно что нибудь нормальное сделать 

### ISSUE THREAD

**Issue by med100s** [SerduM-div/SHIT#8]
Крч нужно продумать какой либо продукт и заебошить что-нибудь нормальное. Понимаешь о чем я ?

**Comment by med100s** [comment]
У меня есть идея сделать какую нибудь простую игру типа ai dungeon чекни чё такое

**Comment by med100s** [comment]
Ну чё ты здесь?

**Comment by med100s** [comment]
Ну же нига давай

**Comment by med100s** [comment]
Ответь мне

**Comment by med100s** [comment]
Бля

**Comment by SerduM-div** [comment]
Я тут

**Comment by SerduM-div** [comment]
Но я щас занят

**Comment by med100s** [comment]
Ок

**Comment by med100s** [comment]
https://habr.com/ru/company/edison/blog/269789/

**Comment by med100s** [comment]
ну хотя я хуй знает,  накидай идеи че хочешь, ну у меня есть идеи но ты тоже предложи

**Comment by med100s** [comment]
![Uploading image.png…]()

**Comment by med100s** [comment]
![image](https://user-images.githubusercontent.com/61676013/108872682-3e38be00-761c-11eb-884c-36e8ea1f046e.png)

**Comment by med100s** [comment]
https://www.youtube.com/watch?v=ivDjWYcKDZI&t=341s
node react ...

**Comment by med100s** [comment]
+ postgresql + mongodb

**Comment by med100s** [comment]
https://www.postgresqltutorial.com/   https://university.mongodb.com/

**Comment by med100s** [comment]
https://www.typescriptlang.org/docs/ typescript

**Comment by med100s** [comment]
https://github.com/chanakaudaya/solution-architecture-patterns архитектура и паттерны 
https://github.com/MostlyAdequate/mostly-adequate-guide-ru книга по фп

**Comment by med100s** [comment]
https://github.com/dotnet/training-tutorials c# плюс f#

**Comment by med100s** [comment]
после этого всего я смогу претенжовать на мидла, затем останется только получить опыта на github'e

**Comment by med100s** [comment]
+ https://www.restapitutorial.com/  рест апи 
+ https://medium.com/quick-code/top-tutorials-to-learn-django-framework-for-python-beginners-fe1a9e315aa9
django

**Comment by med100s** [comment]
последние две сделают меня фул стаком... ну там так то еще подучить немного надо будет , но в принципе можно уже будет попробовать устроиться

**Comment by med100s** [comment]
на мидла прям

**Comment by med100s** [comment]
ну и пару проектов каких нибудь
